# Generated by Django 3.0.5 on 2020-05-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioShare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='demo',
        ),
        migrations.AddField(
            model_name='postfiles',
            name='demo',
            field=models.FileField(default='Backflip.mp3', upload_to='demos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postfiles',
            name='files',
            field=models.FileField(upload_to='files'),
        ),
    ]
