# Generated by Django 3.0.5 on 2020-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioShare', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiles',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='project_pics'),
        ),
    ]
